config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :recipes
  def index; end

  def show
    @recipe = @recipes.find { |r| r.id == params[:id] }
  end

  private

  def recipes
    @recipes ||= Recipes.call
  end
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  # redcarpet markdown
  def markdown(text)
    options = {
        filter_html:     true,
        hard_wrap:       true,
        link_attributes: { rel: 'nofollow', target: "_blank" },
        space_after_headers: true,
        fenced_code_blocks: true
    }
    extensions = {
        autolink:           true,
        superscript:        true,
        disable_indented_code_blocks: true
    }

    renderer = ::Redcarpet::Render::HTML.new(options)
    markdown = ::Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DisplayRecipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>.: OUR AMAZING RECIPES 🍲​​:.</h1>
<div class="container">
  <% if @recipes.nil? %>
    <div class='recipe-index'>
      <p>Sorry, no recipes today ☹️​</p>
    </div>
  <% end %>
  <% @recipes.each do |recipe| %>
    <div class='recipe-index'>
      <a class='recipe-tile' href="<%= recipe_path(recipe.id) %>">
        <img class='recipe-image' src="<%= recipe.photo.url %>" />
        <legend><%= recipe.title %></legend>
      </a>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <% if @recipe.nil? %>
    <div class='recipe-box'>
      <p>Sorry, recipe not found ☹️​</p>
      <p>Let's try other!​</p>
    </div>
  <% else %>
  <div class='recipe-box'>
    <h3><%= @recipe.title %></h3>
    <label><%= "By #{@recipe.chef.name}" if @recipe.fields.key?(:chef) %></label>

    <img class='recipe-image' src="<%= @recipe.photo.url %>" />
    <p><%= markdown(@recipe.description) %></p>
    <em><%= "Tags: #{@recipe.tags.collect(&:name).join(', ')}" if @recipe.fields.key?(:tags) %></em>
  </div>
  <% end %>
</div>
<%= link_to "Back to Start", root_path, class: "back-button" %>